name: Auto Update Branches
on:
    schedule:
        - cron: "*/30 * * * *"
    workflow_dispatch: {}

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    auto-update-branches:
        uses: trilogy-group/ws-lambda-process/.github/workflows/auto-update-branches.yml@master
