name: Auto Release Accepted
on:
    schedule:
        - cron: "*/15 * * * *"
    workflow_dispatch: {}

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    auto-release-accepted:
        uses: trilogy-group/ws-lambda-process/.github/workflows/auto-release-accepted.yml@master
