name: Deploy Infra Dev

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.sha.outputs.short-sha }}
      build-id: ${{ steps.sha.outputs.build-id }}
    steps:
      - id: sha
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "short-sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "build-id=main-${SHORT_SHA}" >> $GITHUB_OUTPUT

  deploy-infra:
    needs: setup
    uses: ./.github/workflows/base-deploy-infra.yml
    with:
      stack-name: AiEduChatDevStack
      default-game-skeleton: ${{ needs.setup.outputs.build-id }}
      sentry-environment: staging
      build-id: staging
      secret-id: ai-first-game-dev/dev/nextjs-secrets
      bucket-name: aieduchatdevstack-gameassetsbucket67e182c3-jfhxd5hpsuhx
    secrets: inherit

  deploy-game:
    needs: setup
    uses: ./.github/workflows/base-deploy-game.yml
    with:
      game-skeleton: SubwaySurfers
      s3-bucket: aieduchatdevstack-gameassetsbucket67e182c3-jfhxd5hpsuhx
      s3-prefix: skeletons/${{ needs.setup.outputs.build-id }}
      sentry-environment: staging
      build-id: staging
    secrets: inherit
