name: Deploy Infra Prod

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      skip_notification:
        description: "Skip post-deployment notification"
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.sha.outputs.short-sha }}
      build-id: ${{ steps.sha.outputs.build-id }}
    steps:
      - id: sha
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "short-sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "build-id=main-${SHORT_SHA}" >> $GITHUB_OUTPUT

  deploy-infra:
    needs: setup
    uses: ./.github/workflows/base-deploy-infra.yml
    with:
      stack-name: AiEduChatProdStack
      aws-role: "arn:aws:iam::010526244253:role/GithubActionsOidcCdkDeployRole"
      default-game-skeleton: ${{ needs.setup.outputs.build-id }}
      sentry-environment: production
      build-id: production
      secret-id: ai-first-game-dev/prod/nextjs-secrets
      bucket-name: aieduchatprodstack-gameassetsbucket67e182c3-yo3xlx66ou2b
    secrets: inherit

  deploy-game:
    needs: setup
    uses: ./.github/workflows/base-deploy-game.yml
    with:
      game-skeleton: SubwaySurfers
      aws-role: "arn:aws:iam::010526244253:role/GithubActionsOidcCdkDeployRole"
      s3-bucket: aieduchatprodstack-gameassetsbucket67e182c3-yo3xlx66ou2b
      s3-prefix: skeletons/${{ needs.setup.outputs.build-id }}
      sentry-environment: production
      build-id: production
    secrets: inherit

  post-deploy-notification:
    needs: [deploy-infra, deploy-game]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: success() && !inputs.skip_notification
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Post release notes
        uses: trilogy-group/ws-eng-cli@main
        with:
          type: ts-only
          command: wseng rn
