name: PR Review

on:
  pull_request:
    types: [ready_for_review, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  review-pr:
    if: github.event.pull_request.draft == false
    uses: trilogy-group/ws-lambda-process/.github/workflows/review-pr.yml@master
